### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by agriffard**

### CODE REVIEW

**Comment by sebastienros** [comment]
Smells like automatic translations, at least for the French one.

**Comment by agriffard** [comment]
> Smells like automatic translations, at least for the French one.

Those are my translations. 
Some of them may seem strange because I chose to keep English words (while the ML translation was suggesting a translation in French).
Ex for the OpenId: I didn't want to translate technical words like token, Client credentials, Hybrid Flow, on purpose.

**Comment by sebastienros** [comment]
"Cliquez sur ici" for "Click here" ...

**Comment by agriffard** [comment]
> "Cliquez sur ici" for "Click here" ...

OK, thank you, fixed on Crowdin.

**Pull request merged**
